take pack
examine papers
take paperclip
open panel
insert paperclip into panel
s
sw
n
take shelf
s
e
w
examine maker
take filter
s
take knife
w
take crowbar
s
take tree
s
take wd40
n
n
e
n
e
se
spray helmet with wd40
take helmet
insert filter into helmet
s
take pestle
n
cut hand with knife
take hand
crush tree
take charcoal
insert charcoal into helmet
wear helmet
w
e
s
take brush
n
w
s
pry door
se
scan hand
turn switch
n
n
e
e
examine jacket
take code book
w
w
s
se
e
d
unblock pipe
u
w
w
turn radio
type
type
w
w
n
e
turn valve
take hose
w
n
e
n
e
s
sw
put hose on gas tank
turn dial
n
se
e
weld knob with nozzle
put crowbar on knob
turn knob
w
n
n
n
open external door
n
