turn on lamp
d
get fruit
d
drop fruit
get all
u
open stove
put cheese in it
close stove
turn it on
turn it off
open it
look under rug
get glove
wear it
get key
unlock cupboard
open it
get cog
u
put cog in lamp
turn on lamp
d
d
out
e
look at painting
ask barman about painting
w
s
e
e
s
x scarecrow
get rod
n
w
w
n
e
n
look in well
get coin with rod
get all
s
w
s
w
z
z
z
enter bus
give coin to driver
s
e
drop mouse
get crumbs
w
s
e
x ring
enter portal
e
s
e
e
s
wear ring
say sammy
get oar
n
w
s
feed ducks
enter boat
paddle
exit
s
get spade
e
n
put sand in glass
s
put glass on block
get figurine
n
w
enter boat
paddle
exit
n
w
n
w
enter portal
give figurine to man
x gold ring
w
n
w
give spade to shopkeeper
e
s
e
enter portal
e
s
e
e
n
wear gold ring
say liner
x lion
x zebra
x penguin
x toucan
x pelican
press lion
press zebra
press penguin
press pelican
n
x earth
dig disturbed patch with spade
get figure
s
s
w
w
n
w
enter portal
give figure to man
x obsidian ring
enter portal
e
wear obsidian ring
x pillar
say citra
quit
yes
